### ISSUE TITLE
ამ მოდელს აკლია მეტა კლასი, __str__ მეთოდი და ფილდებს verbose_name ები

### ISSUE THREAD

**Issue by MariamKipshidze** [sandroin/Learning-Management-System#27]
https://github.com/sandroin/Learning-Management-System/blob/3e25f1da6a22ea21fecbe69143a796bf7bfa2fee/lms_app/models.py#L79

**Comment by NiaGerg** [comment]
Done

**Comment by NiaGerg** [comment]
Done
